<a href="https://colab.research.google.com/github/ghevia99-CAN/Python-Data-Analysis/blob/main/Numpy1_Array_and_more_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numeric Python  - NumPay Array

In [26]:
#Python list
my_list = [1,2,3,4,5,6,7,8,9,"Bob", True]
print(my_list)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Bob', True]


In [27]:
# Import NumPy
import numpy as np

In [29]:
# Create a Numpy array
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1[2])


3


In [30]:
# Shape - Show the number of elements in the array, like the python len function
print(np1.shape)


(9,)


In [32]:
# Arange
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
np3 = np.arange(0,12,2)
print (np3)


[ 0  2  4  6  8 10]


In [34]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
# Multi- Dimensional Arrays with Zeros
np5 = np.zeros((2,10))
print(np5)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
# Full
np6 = np.full((10), 6)
print(np6)


[6 6 6 6 6 6 6 6 6 6]


In [37]:
# Multi-Dimensional array with full
np7 = np.full((2,10),41)
print (np7)


[[41 41 41 41 41 41 41 41 41 41]
 [41 41 41 41 41 41 41 41 41 41]]


In [38]:
# Convert a Python List in a Numpy Array - Check the difference how it shows the items from a
# my_list                          Python list compared to a Numpy array
np8 = np.array(my_list)
print(np8)
print(my_list)

['1' '2' '3' '4' '5' '6' '7' '8' '9' 'Bob' 'True']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'Bob', True]
