<a href="https://colab.research.google.com/github/ghevia99-CAN/Python-Data-Analysis/blob/main/Numpy_3_Slices_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Slicing Numpy Array = Return 2,3,4,5
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1[1:5]) # 5 is up till but not including 5

[2 3 4 5]


In [ ]:
#Return from something till end or array
print(np1[3: ]) # :nothing means till the end


[4 5 6 7 8 9]


In [ ]:
# Return negative slices, from the end backwards
print(np1[-3:-1]) # -1 is up till but not including -1


[7 8]


In [ ]:
# Slices with Steps
print(np1[1:5])
print(np1[1:5:2]) # it shows the 1th to the 5th element, up till the 5th, the third parameters indicates how many items stepping, every two items


[2 3 4 5]
[2 4]


In [ ]:
# Slices whole thing in steps
print(np1)
print(np1[::2]) # It shows all, but stepping every two positions,so it shows less data



[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
